
FROM openjdk:JDK_VERSION_TAG-jdk

# ENV vars
ENV TERM xterm-256color
ENV SCALA_VERSION SCALA_VERSION_TAG
ENV SBT_VERSION SBT_VERSION_TAG

# add additional packages and upgrade OS
#  NOTE: in order to install newest docker - need to add diff source list
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates wget tree htop zip unzip gnupg && \
   apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
   echo "deb https://apt.dockerproject.org/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list && \
   apt-get update && apt-get install -y docker-engine && \
   apt-get upgrade -y && apt-get clean && \
   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# install scala and sbt
RUN wget http://www.scala-lang.org/files/archive/scala-${SCALA_VERSION}.deb && \
    wget http://dl.bintray.com/sbt/debian/sbt-${SBT_VERSION}.deb && \
    dpkg -i scala-${SCALA_VERSION}.deb && \
    dpkg -i sbt-${SBT_VERSION}.deb && \
    rm -rf /*.deb

# Force a download of the Scala libraries.
RUN sbt "set scalaVersion := \"$SCALA_VERSION\"" compile

# add labels for easy identification
LABEL JAVA_VERSION=$JAVA_VERSION
LABEL SCALA_VERSION=$SCALA_VERSION
LABEL SBT_VERSION=$SBT_VERSION

# add generated Dockerfile for easy viewing
ADD Dockerfile .
